Repository mlr-org/mlr3gallery, pull requests merged in 2020-05, with the labels that each got.

#31 Cleanup imbalanced data
  .github/workflows/main.yml
  _posts/2020-03-30-imbalanced-data/2020-03-30-imbalanced-data.Rmd
  _posts/2020-03-30-imbalanced-data/2020-03-30-imbalanced-data.html
  _posts/2020-03-30-imbalanced-data/2020-03-30-imbalanced-data_files/figure-html5/unnamed-chunk-11-1.png
  _posts/2020-03-30-imbalanced-data/2020-03-30-imbalanced-data_files/figure-html5/unnamed-chunk-12-1.png
  _posts/2020-03-30-imbalanced-data/biblio.bib
Labels: Status: Accepted, Type: Optimization

#16 Post: mlr3 and OpenML - Moneyball use case
  DESCRIPTION
  _posts/2020-03-18-iris-mlr3-basics/2020-03-18-iris-mlr3-basics.Rmd
  _posts/2020-03-18-iris-mlr3-basics/2020-03-18-iris-mlr3-basics.html
  _posts/2020-05-04-moneyball/2020-05-04-moneyball.Rmd
  docs/about.html
  docs/index.html
  docs/index.xml
  docs/posts/2020-03-18-iris-mlr3-basics/index.html
  docs/posts/2020-05-04-moneyball/index.html
  docs/posts/posts.json
  docs/site_libs/htmlwidgets-1.5.1/htmlwidgets.js
  docs/site_libs/vis-4.20.1/img/network/acceptDeleteIcon.png
  docs/site_libs/vis-4.20.1/img/network/addNodeIcon.png
  docs/site_libs/vis-4.20.1/img/network/backIcon.png
  docs/site_libs/vis-4.20.1/img/network/connectIcon.png
  docs/site_libs/vis-4.20.1/img/network/cross.png
  docs/site_libs/vis-4.20.1/img/network/cross2.png
  docs/site_libs/vis-4.20.1/img/network/deleteIcon.png
  docs/site_libs/vis-4.20.1/img/network/downArrow.png
  docs/site_libs/vis-4.20.1/img/network/editIcon.png
  docs/site_libs/vis-4.20.1/img/network/leftArrow.png
  docs/site_libs/vis-4.20.1/img/network/minus.png
  docs/site_libs/vis-4.20.1/img/network/plus.png
  docs/site_libs/vis-4.20.1/img/network/rightArrow.png
  docs/site_libs/vis-4.20.1/img/network/upArrow.png
  docs/site_libs/vis-4.20.1/img/network/zoomExtends.png
  docs/site_libs/vis-4.20.1/vis.css
  docs/site_libs/vis-4.20.1/vis.min.js
  docs/site_libs/visNetwork-binding-2.0.9/visNetwork.js
  docs/sitemap.xml
Labels: Status: In Progress

#41 Titanic Separation
  DESCRIPTION
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-intro-pipelines-titanic.Rmd
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics.Rmd
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics.html
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/bowser-1.9.3/bowser.min.js
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/distill-2.2.21/template.v2.js
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/figure-html5/unnamed-chunk-5-1.png
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/figure-html5/unnamed-chunk-6-1.png
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/figure-html5/unnamed-chunk-6-2.png
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/header-attrs-2.1/header-attrs.js
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/jquery-1.11.3/jquery.min.js
  _posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/webcomponents-2.0.0/webcomponents.js
  _posts/2020-04-27-mlr3pipelines-Imputation-titanic/2020-04-27-mlr3pipelines-titanic-advanced.Rmd
  docs/DESCRIPTION
  docs/index.html
  docs/index.xml
  docs/posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/bowser-1.9.3/bowser.min.js
  docs/posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/distill-2.2.21/template.v2.js
  docs/posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/figure-html5/unnamed-chunk-5-1.png
  docs/posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/figure-html5/unnamed-chunk-6-1.png
  docs/posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/figure-html5/unnamed-chunk-6-2.png
  docs/posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/header-attrs-2.1/header-attrs.js
  docs/posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/jquery-1.11.3/jquery.min.js
  docs/posts/2020-03-12-intro-pipelines-titanic/2020-03-12-mlr3pipelines-titanic-Basics/webcomponents-2.0.0/webcomponents.js
  docs/posts/2020-03-12-intro-pipelines-titanic/index.html
  docs/posts/posts.json
  docs/sitemap.xml
Labels: Status: Revision Needed, Type: Optimization
